name: Node Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  acceptance_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PGUSER: postgres
          POSTGRES_DB: flight_booker_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout the Backend
        uses: actions/checkout@v3
        with:
          repository: abhi8080/FlightBooker-backend
          ref: master
          path: backend

      - name: Checkout the Frontend
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./backend

      - name: Migrate tables to database
        run: dotnet new tool-manifest && dotnet tool install dotnet-ef && dotnet ef database update
        working-directory: ./backend

      - name: Start Backend
        run: dotnet run&
        working-directory: ./backend

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Install Playwright Dependencies
        run: npx playwright install
        working-directory: ./frontend

      - name: Install Playwright Browsers
        run: npx playwright install-deps
        working-directory: ./frontend

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./frontend

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
